package com.gr.jiang.domain;

public class Financeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.FINANCE_ID
     *
     * @mbggenerated
     */
    private Long financeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.domain
     *
     * @mbggenerated
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.ORGAN
     *
     * @mbggenerated
     */
    private String organ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.FIN_NAME
     *
     * @mbggenerated
     */
    private String finName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.PRO_BATE
     *
     * @mbggenerated
     */
    private String proBate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.USER_NUM
     *
     * @mbggenerated
     */
    private String userNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.BEGIN_AMT
     *
     * @mbggenerated
     */
    private String beginAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.PRO_CYCLE
     *
     * @mbggenerated
     */
    private String proCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.PRO_SIZE
     *
     * @mbggenerated
     */
    private String proSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.ALL_AMT
     *
     * @mbggenerated
     */
    private String allAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.CAN_AMT
     *
     * @mbggenerated
     */
    private String canAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.BUY_BUTTON
     *
     * @mbggenerated
     */
    private String buyButton;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.BUY_URL
     *
     * @mbggenerated
     */
    private String buyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.PRO_FLAG
     *
     * @mbggenerated
     */
    private String proFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.FROM_URL
     *
     * @mbggenerated
     */
    private String fromUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.PROCESS
     *
     * @mbggenerated
     */
    private String process;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.HA_STR
     *
     * @mbggenerated
     */
    private String haStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.CRE_DT
     *
     * @mbggenerated
     */
    private String creDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.CRE_TM
     *
     * @mbggenerated
     */
    private String creTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.CRE_DM
     *
     * @mbggenerated
     */
    private String creDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCEINFO.TM_SMP
     *
     * @mbggenerated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.FINANCE_ID
     *
     * @return the value of FINANCEINFO.FINANCE_ID
     *
     * @mbggenerated
     */
    public Long getFinanceId() {
        return financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.FINANCE_ID
     *
     * @param financeId the value for FINANCEINFO.FINANCE_ID
     *
     * @mbggenerated
     */
    public void setFinanceId(Long financeId) {
        this.financeId = financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.domain
     *
     * @return the value of FINANCEINFO.domain
     *
     * @mbggenerated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.domain
     *
     * @param domain the value for FINANCEINFO.domain
     *
     * @mbggenerated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.ORGAN
     *
     * @return the value of FINANCEINFO.ORGAN
     *
     * @mbggenerated
     */
    public String getOrgan() {
        return organ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.ORGAN
     *
     * @param organ the value for FINANCEINFO.ORGAN
     *
     * @mbggenerated
     */
    public void setOrgan(String organ) {
        this.organ = organ == null ? null : organ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.FIN_NAME
     *
     * @return the value of FINANCEINFO.FIN_NAME
     *
     * @mbggenerated
     */
    public String getFinName() {
        return finName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.FIN_NAME
     *
     * @param finName the value for FINANCEINFO.FIN_NAME
     *
     * @mbggenerated
     */
    public void setFinName(String finName) {
        this.finName = finName == null ? null : finName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.PRO_BATE
     *
     * @return the value of FINANCEINFO.PRO_BATE
     *
     * @mbggenerated
     */
    public String getProBate() {
        return proBate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.PRO_BATE
     *
     * @param proBate the value for FINANCEINFO.PRO_BATE
     *
     * @mbggenerated
     */
    public void setProBate(String proBate) {
        this.proBate = proBate == null ? null : proBate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.USER_NUM
     *
     * @return the value of FINANCEINFO.USER_NUM
     *
     * @mbggenerated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.USER_NUM
     *
     * @param userNum the value for FINANCEINFO.USER_NUM
     *
     * @mbggenerated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.BEGIN_AMT
     *
     * @return the value of FINANCEINFO.BEGIN_AMT
     *
     * @mbggenerated
     */
    public String getBeginAmt() {
        return beginAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.BEGIN_AMT
     *
     * @param beginAmt the value for FINANCEINFO.BEGIN_AMT
     *
     * @mbggenerated
     */
    public void setBeginAmt(String beginAmt) {
        this.beginAmt = beginAmt == null ? null : beginAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.PRO_CYCLE
     *
     * @return the value of FINANCEINFO.PRO_CYCLE
     *
     * @mbggenerated
     */
    public String getProCycle() {
        return proCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.PRO_CYCLE
     *
     * @param proCycle the value for FINANCEINFO.PRO_CYCLE
     *
     * @mbggenerated
     */
    public void setProCycle(String proCycle) {
        this.proCycle = proCycle == null ? null : proCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.PRO_SIZE
     *
     * @return the value of FINANCEINFO.PRO_SIZE
     *
     * @mbggenerated
     */
    public String getProSize() {
        return proSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.PRO_SIZE
     *
     * @param proSize the value for FINANCEINFO.PRO_SIZE
     *
     * @mbggenerated
     */
    public void setProSize(String proSize) {
        this.proSize = proSize == null ? null : proSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.ALL_AMT
     *
     * @return the value of FINANCEINFO.ALL_AMT
     *
     * @mbggenerated
     */
    public String getAllAmt() {
        return allAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.ALL_AMT
     *
     * @param allAmt the value for FINANCEINFO.ALL_AMT
     *
     * @mbggenerated
     */
    public void setAllAmt(String allAmt) {
        this.allAmt = allAmt == null ? null : allAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.CAN_AMT
     *
     * @return the value of FINANCEINFO.CAN_AMT
     *
     * @mbggenerated
     */
    public String getCanAmt() {
        return canAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.CAN_AMT
     *
     * @param canAmt the value for FINANCEINFO.CAN_AMT
     *
     * @mbggenerated
     */
    public void setCanAmt(String canAmt) {
        this.canAmt = canAmt == null ? null : canAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.BUY_BUTTON
     *
     * @return the value of FINANCEINFO.BUY_BUTTON
     *
     * @mbggenerated
     */
    public String getBuyButton() {
        return buyButton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.BUY_BUTTON
     *
     * @param buyButton the value for FINANCEINFO.BUY_BUTTON
     *
     * @mbggenerated
     */
    public void setBuyButton(String buyButton) {
        this.buyButton = buyButton == null ? null : buyButton.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.BUY_URL
     *
     * @return the value of FINANCEINFO.BUY_URL
     *
     * @mbggenerated
     */
    public String getBuyUrl() {
        return buyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.BUY_URL
     *
     * @param buyUrl the value for FINANCEINFO.BUY_URL
     *
     * @mbggenerated
     */
    public void setBuyUrl(String buyUrl) {
        this.buyUrl = buyUrl == null ? null : buyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.PRO_FLAG
     *
     * @return the value of FINANCEINFO.PRO_FLAG
     *
     * @mbggenerated
     */
    public String getProFlag() {
        return proFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.PRO_FLAG
     *
     * @param proFlag the value for FINANCEINFO.PRO_FLAG
     *
     * @mbggenerated
     */
    public void setProFlag(String proFlag) {
        this.proFlag = proFlag == null ? null : proFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.FROM_URL
     *
     * @return the value of FINANCEINFO.FROM_URL
     *
     * @mbggenerated
     */
    public String getFromUrl() {
        return fromUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.FROM_URL
     *
     * @param fromUrl the value for FINANCEINFO.FROM_URL
     *
     * @mbggenerated
     */
    public void setFromUrl(String fromUrl) {
        this.fromUrl = fromUrl == null ? null : fromUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.PROCESS
     *
     * @return the value of FINANCEINFO.PROCESS
     *
     * @mbggenerated
     */
    public String getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.PROCESS
     *
     * @param process the value for FINANCEINFO.PROCESS
     *
     * @mbggenerated
     */
    public void setProcess(String process) {
        this.process = process == null ? null : process.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.HA_STR
     *
     * @return the value of FINANCEINFO.HA_STR
     *
     * @mbggenerated
     */
    public String getHaStr() {
        return haStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.HA_STR
     *
     * @param haStr the value for FINANCEINFO.HA_STR
     *
     * @mbggenerated
     */
    public void setHaStr(String haStr) {
        this.haStr = haStr == null ? null : haStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.CRE_DT
     *
     * @return the value of FINANCEINFO.CRE_DT
     *
     * @mbggenerated
     */
    public String getCreDt() {
        return creDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.CRE_DT
     *
     * @param creDt the value for FINANCEINFO.CRE_DT
     *
     * @mbggenerated
     */
    public void setCreDt(String creDt) {
        this.creDt = creDt == null ? null : creDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.CRE_TM
     *
     * @return the value of FINANCEINFO.CRE_TM
     *
     * @mbggenerated
     */
    public String getCreTm() {
        return creTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.CRE_TM
     *
     * @param creTm the value for FINANCEINFO.CRE_TM
     *
     * @mbggenerated
     */
    public void setCreTm(String creTm) {
        this.creTm = creTm == null ? null : creTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.CRE_DM
     *
     * @return the value of FINANCEINFO.CRE_DM
     *
     * @mbggenerated
     */
    public String getCreDm() {
        return creDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.CRE_DM
     *
     * @param creDm the value for FINANCEINFO.CRE_DM
     *
     * @mbggenerated
     */
    public void setCreDm(String creDm) {
        this.creDm = creDm == null ? null : creDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCEINFO.TM_SMP
     *
     * @return the value of FINANCEINFO.TM_SMP
     *
     * @mbggenerated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCEINFO.TM_SMP
     *
     * @param tmSmp the value for FINANCEINFO.TM_SMP
     *
     * @mbggenerated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}