package com.gr.jiang.domain;

public class ScrapyContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.CONTENT_ID
     *
     * @mbggenerated
     */
    private Long contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.DOMIN_ID
     *
     * @mbggenerated
     */
    private Long dominId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.CONTENT_COLNUM
     *
     * @mbggenerated
     */
    private String contentColnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.CONTENT_URL
     *
     * @mbggenerated
     */
    private String contentUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.CONTENT_RE_URL
     *
     * @mbggenerated
     */
    private String contentReUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.CONTENT_RE_ISFOLLOW
     *
     * @mbggenerated
     */
    private String contentReIsfollow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.CONTENT_START_DT
     *
     * @mbggenerated
     */
    private String contentStartDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.CONTENT_END_DT
     *
     * @mbggenerated
     */
    private String contentEndDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.CONTENT_URL_FLAG
     *
     * @mbggenerated
     */
    private String contentUrlFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.CONTENT_STS
     *
     * @mbggenerated
     */
    private String contentSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.TM_SMP
     *
     * @mbggenerated
     */
    private String tmSmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCRAPY_CONTENT.CONTENT_HANDLE_FUND
     *
     * @mbggenerated
     */
    private String contentHandleFund;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.CONTENT_ID
     *
     * @return the value of SCRAPY_CONTENT.CONTENT_ID
     *
     * @mbggenerated
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.CONTENT_ID
     *
     * @param contentId the value for SCRAPY_CONTENT.CONTENT_ID
     *
     * @mbggenerated
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.DOMIN_ID
     *
     * @return the value of SCRAPY_CONTENT.DOMIN_ID
     *
     * @mbggenerated
     */
    public Long getDominId() {
        return dominId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.DOMIN_ID
     *
     * @param dominId the value for SCRAPY_CONTENT.DOMIN_ID
     *
     * @mbggenerated
     */
    public void setDominId(Long dominId) {
        this.dominId = dominId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.CONTENT_COLNUM
     *
     * @return the value of SCRAPY_CONTENT.CONTENT_COLNUM
     *
     * @mbggenerated
     */
    public String getContentColnum() {
        return contentColnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.CONTENT_COLNUM
     *
     * @param contentColnum the value for SCRAPY_CONTENT.CONTENT_COLNUM
     *
     * @mbggenerated
     */
    public void setContentColnum(String contentColnum) {
        this.contentColnum = contentColnum == null ? null : contentColnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.CONTENT_URL
     *
     * @return the value of SCRAPY_CONTENT.CONTENT_URL
     *
     * @mbggenerated
     */
    public String getContentUrl() {
        return contentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.CONTENT_URL
     *
     * @param contentUrl the value for SCRAPY_CONTENT.CONTENT_URL
     *
     * @mbggenerated
     */
    public void setContentUrl(String contentUrl) {
        this.contentUrl = contentUrl == null ? null : contentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.CONTENT_RE_URL
     *
     * @return the value of SCRAPY_CONTENT.CONTENT_RE_URL
     *
     * @mbggenerated
     */
    public String getContentReUrl() {
        return contentReUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.CONTENT_RE_URL
     *
     * @param contentReUrl the value for SCRAPY_CONTENT.CONTENT_RE_URL
     *
     * @mbggenerated
     */
    public void setContentReUrl(String contentReUrl) {
        this.contentReUrl = contentReUrl == null ? null : contentReUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.CONTENT_RE_ISFOLLOW
     *
     * @return the value of SCRAPY_CONTENT.CONTENT_RE_ISFOLLOW
     *
     * @mbggenerated
     */
    public String getContentReIsfollow() {
        return contentReIsfollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.CONTENT_RE_ISFOLLOW
     *
     * @param contentReIsfollow the value for SCRAPY_CONTENT.CONTENT_RE_ISFOLLOW
     *
     * @mbggenerated
     */
    public void setContentReIsfollow(String contentReIsfollow) {
        this.contentReIsfollow = contentReIsfollow == null ? null : contentReIsfollow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.CONTENT_START_DT
     *
     * @return the value of SCRAPY_CONTENT.CONTENT_START_DT
     *
     * @mbggenerated
     */
    public String getContentStartDt() {
        return contentStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.CONTENT_START_DT
     *
     * @param contentStartDt the value for SCRAPY_CONTENT.CONTENT_START_DT
     *
     * @mbggenerated
     */
    public void setContentStartDt(String contentStartDt) {
        this.contentStartDt = contentStartDt == null ? null : contentStartDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.CONTENT_END_DT
     *
     * @return the value of SCRAPY_CONTENT.CONTENT_END_DT
     *
     * @mbggenerated
     */
    public String getContentEndDt() {
        return contentEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.CONTENT_END_DT
     *
     * @param contentEndDt the value for SCRAPY_CONTENT.CONTENT_END_DT
     *
     * @mbggenerated
     */
    public void setContentEndDt(String contentEndDt) {
        this.contentEndDt = contentEndDt == null ? null : contentEndDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.CONTENT_URL_FLAG
     *
     * @return the value of SCRAPY_CONTENT.CONTENT_URL_FLAG
     *
     * @mbggenerated
     */
    public String getContentUrlFlag() {
        return contentUrlFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.CONTENT_URL_FLAG
     *
     * @param contentUrlFlag the value for SCRAPY_CONTENT.CONTENT_URL_FLAG
     *
     * @mbggenerated
     */
    public void setContentUrlFlag(String contentUrlFlag) {
        this.contentUrlFlag = contentUrlFlag == null ? null : contentUrlFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.CONTENT_STS
     *
     * @return the value of SCRAPY_CONTENT.CONTENT_STS
     *
     * @mbggenerated
     */
    public String getContentSts() {
        return contentSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.CONTENT_STS
     *
     * @param contentSts the value for SCRAPY_CONTENT.CONTENT_STS
     *
     * @mbggenerated
     */
    public void setContentSts(String contentSts) {
        this.contentSts = contentSts == null ? null : contentSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.TM_SMP
     *
     * @return the value of SCRAPY_CONTENT.TM_SMP
     *
     * @mbggenerated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.TM_SMP
     *
     * @param tmSmp the value for SCRAPY_CONTENT.TM_SMP
     *
     * @mbggenerated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCRAPY_CONTENT.CONTENT_HANDLE_FUND
     *
     * @return the value of SCRAPY_CONTENT.CONTENT_HANDLE_FUND
     *
     * @mbggenerated
     */
    public String getContentHandleFund() {
        return contentHandleFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCRAPY_CONTENT.CONTENT_HANDLE_FUND
     *
     * @param contentHandleFund the value for SCRAPY_CONTENT.CONTENT_HANDLE_FUND
     *
     * @mbggenerated
     */
    public void setContentHandleFund(String contentHandleFund) {
        this.contentHandleFund = contentHandleFund == null ? null : contentHandleFund.trim();
    }
}