package com.gr.jiang.mapper;

import com.gr.jiang.domain.Financeinfo;

public interface FinanceinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCEINFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long financeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCEINFO
     *
     * @mbggenerated
     */
    int insert(Financeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCEINFO
     *
     * @mbggenerated
     */
    int insertSelective(Financeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCEINFO
     *
     * @mbggenerated
     */
    Financeinfo selectByPrimaryKey(Long financeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCEINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Financeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCEINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Financeinfo record);
}